#!/bin/bash
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
python ./aug-imagenet-1-class.py&
